config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  #routing to be fixed later
  resources :tasks

  resources :categories do
    resources :tasks
  end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :tasks, dependent: :destroy
    validates :name, presence: true,
                     length: { minimum: 3 }

    # Everytime after deleting a category, create the default Inbox when there is no more category,
    # so that there is still a category for users to choose from
    after_commit :create_default, on: :destroy
    # create a default Inbox category
    def create_default
        unless Category.exists?
            Category.create :name => 'Inbox', :description => 'Default category'
        end
    end
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  #simple authentication, where only one user is created for testing purposes
  http_basic_authenticate_with name: "cvwo2018", password: "cvwo2018", only: :index

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        flash[:success] = 'Category was successfully created.'
        format.html { redirect_to @category }
        format.json { render :show, status: :created, location: @category }
      else
        flash[:danger] = 'There was a problem creating the Category.'
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        flash[:success] = 'Category was successfully updated.'
        format.html { redirect_to @category }
        format.json { render :show, status: :ok, location: @category }
      else
        flash[:danger] = 'There was a problem updating the Category.'
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      flash[:success] = 'Category was successfully deleted.'
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  #simple authentication, where only one user is created for testing purposes
  http_basic_authenticate_with name: "cvwo2018", password: "cvwo2018", only: :index
  
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end
 
  # GET /tasks/new
  def new
    @task = Task.new
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  # GET /tasks/1/edit
  def edit
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.category_id = params[:category_id]
    
    respond_to do |format|
      if @task.save
        flash[:success] = 'Task was successfully created.'
        format.html { redirect_to @task }
        format.json { render :show, status: :created, location: @task }
      else
        flash[:danger] = 'There was a problem creating the Task.'
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    @task.category_id = params[:category_id]

    respond_to do |format|
      if @task.update(task_params)
        flash[:success] = 'Task was successfully updated.'
        format.html { redirect_to @task }
        format.json { render :show, status: :ok, location: @task }
      else
        flash[:danger] = 'There was a problem updating the Task.'
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      flash[:success] = 'Task was successfully deleted.'
      format.html { redirect_to tasks_path }
      format.json { head :no_content }
    end
  end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:task_name, :deadline, :details, :category_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h3>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :category_description, class: "form-control" %>
  </div>

  <div class="action">
    <%= form.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<p>
<%= render 'form', category: @category %>
</p>

<%= link_to 'Show This Category', @category, class: 'btn btn-primary btn-sm' %> |
<%= link_to 'Back to All Categories', categories_path, class: 'btn btn-primary btn-sm' %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Categories</h1>

<table class="table table-striped table-hover table-responsive">
  <thead>
    <tr>
      <th class="col-md-3">Name</th>
      <th class="col-md-6">Description</th>
      <th class="col-md-1">Show</th>
      <th class="col-md-1">Edit</th>
      <th class="col-md-1">Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'View', category, class: 'btn btn-info btn-xs' %></td>
        <td><%= link_to edit_category_path(category), class: 'btn btn-warning btn-xs' do %>
              <i class= 'glyphicon glyphicon-pencil'></i>
            <% end %>
        </td>
        <td><%= link_to category, class: 'btn btn-danger btn-xs',
                method: :delete, 
                data: { confirm: 'Are you sure?' } do %>
              <i class= 'glyphicon glyphicon-trash'></i>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path, class: 'btn btn-primary btn-sm' %> |
<%= link_to 'View All Tasks', tasks_path, class: 'btn btn-primary btn-sm' %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<p>
<%= render 'form', category: @category %>
</p>

<%= link_to 'Back', categories_path, class: 'btn btn-primary btn-sm' %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Your Category Details</h1>

<table class="table table-striped table-hover table-responsive table-bordered"> 
  <tbody>
    <tr>
      <td class= "col-md-2"><strong>Category Name</strong></td>
      <td class= "col-md-10"><%= @category.name %></td>
    </tr>

    <tr>
      <td class= "col-md-2"><strong>Description</strong></td>
      <td class= "col-md-10"><%= @category.description %></td>
    </tr>
  </tbody>
</table>


<h2> Tasks under this category </h2>

<table class="table table-striped table-hover table-responsive">
  <tbody>
    <% Task.where(category_id: @category.id).each do |task| %>
      <tr>
        <td class= "col-md-5"><%= task.task_name %></td>
        <td class= "col-md-5"><%= task.deadline %></td>
        <td class= "col-md-2"><%= link_to 'View Task', task_path(task), class: 'btn btn-info btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Edit This Category', edit_category_path(@category), class: 'btn btn-warning btn-sm' %> |
<%= link_to 'Back to All Categories', categories_path, class: 'btn btn-primary btn-sm' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navigation' %>
      <div id="main-container" class="container">
        <div class="row">
          <div class="col-xs-12">
            <% flash.each do |name, msg| -%>
              <%= content_tag :div, msg, class: "alert alert-#{name}" %>
            <% end -%>
          </div>
        </div>

        <div class="jumbotron jumbotron-fluid">
          <div class="container">
            <center>
              <h1 class="display-4">Welcome to Your Todo List</h1>
              <p class="lead">Get your everyday life organized.</p>
            </center>
          </div>
        </div>
        <div>
          <%= yield %>
        </div>
      </div>

    <br>
    <br>
    
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<nav class="navbar fixed-bottom navbar-light bg-faded">
  <div class="row">
    <div class="col-xs-2">
    </div>
    <div class="col-xs-10">
      <div class="navbar-text">
        <blockquote class="blockquote-reverse">
          <p>Start by doing what's necessary; then do what's possible; and suddenly you are doing the impossible.</p>
          <footer>Francis Of Assisi</footer>
        </blockquote>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default", style="background-color: #e3f2fd;">
  <div class="container">
    <div class="navbar-nav">
      <a class="navbar-brand" href="/">Home</a>
      <a class="navbar-brand" href="/tasks">My Todo List</a>
      <a class="navbar-brand" href="/categories">My Categories</a>
    </div>
  </div>
</nav>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h3>

      <ul>
        <% @task.errors.full_messages.each do |messages| %>
          <li><%= messages %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="form-group">
    <%= form.label :task_name %>
    <%= form.text_field :task_name, id: :task_name, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= form.label :Deadline %>
    <%= form.date_field :deadline, id: :task_deadline, class: "form-control" %> 
  </div>

  <div class="form-group">
    <%= form.label :details %><br>
    <%= form.text_area :details, id: :task_details, class: "form-control" %>
  </div>

  <div class ="form-group">
    <div class="row">
      <div class="col-xs-3">
        <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select Category", class: "form-control") %>
      </div>
      <div class="col-xs-9">
      </div>
    </div>
  </div>

  <div class="action">
    <%= form.submit class: "btn btn-default"%>
  </p>
  
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>
 
<%= render 'form', task: @task %>

<%= link_to 'Show This Task', @task, class: 'btn btn-primary btn-sm' %> |
<%= link_to 'Back to All Tasks', tasks_path, class: 'btn btn-primary btn-sm' %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Tasks</h1>

<table class="table table-striped table-hover table-responsive">
  <thead>
    <tr>
      <th class="col-md-2">Task</th>
      <th class="col-md-2">Due Date</th>
      <th class="col-md-3">Details</th>
      <th class="col-md-2">Category</th>
      <th class="col-md-1">Show</th>
      <th class="col-md-1">Edit</th>
      <th class="col-md-1">Delete</th>
    </tr>
  </thead>
 
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.task_name %></td>
        <td><%= task.deadline %></td>
        <td><%= task.details %></td>
        <td><%= link_to category_path(task.category_id), class: 'btn btn-primary btn-xs' do %>
              <%= Category.find(task.category_id).name %> <i class= 'glyphicon glyphicon-tags'></i>
            <% end %>
        </td>
        <td><%= link_to 'View', task_path(task), class: 'btn btn-info btn-xs' %></td>
        <td><%= link_to edit_task_path(task), class: 'btn btn-warning btn-xs' do %>
              <i class= 'glyphicon glyphicon-pencil'></i>
            <% end %>
        </td>
        <td><%= link_to task_path(task), class: 'btn btn-danger btn-xs',
                method: :delete,
                data: { confirm: 'Are you sure?' }  do %>
              <i class= 'glyphicon glyphicon-trash'></i>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'New Task', new_task_path, class: 'btn btn-primary btn-sm' %> |
<%= link_to 'View All Categories', categories_path, class: 'btn btn-primary btn-sm' %>

app/views/tasks/new.html.erb
<h1>New Task</h1>
 
<%= render 'form', task: @task%>
 
<%= link_to 'Back', tasks_path, class: 'btn btn-primary btn-sm' %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Your Task Details</h1>

<table class="table table-striped table-hover table-responsive table-bordered"> 
  <tbody>
    <tr>
      <td class= "col-md-2"><strong>Task Name</strong></td>
      <td class= "col-md-10"><%= @task.task_name %></td>
    </tr>

    <tr>
      <td class= "col-md-2"><strong>Deadline</strong></td>
      <td class= "col-md-10"><%= @task.deadline %></td>
    </tr>

    <tr>
      <td class= "col-md-2"><strong>Category</strong></td>
      <td class= "col-md-10">
        <%= link_to category_path(@task.category_id), class: 'btn btn-primary btn-xs' do %>
              <%= Category.find(@task.category_id).name %> <i class= 'glyphicon glyphicon-tags'></i>
        <% end %>
      </td>
    </tr>

    <tr>
      <td class= "col-md-2"><strong>Details</strong></td>
      <td class= "col-md-10"><%= @task.details %></td>
    </tr>
  </tbody>
</table>


<%= link_to 'Edit This Task', edit_task_path(@task), class: 'btn btn-warning btn-sm' %> |
<%= link_to 'Back to All Tasks', tasks_path, class: 'btn btn-primary btn-sm' %>

app/views/welcome/index.html.erb
<p>
<%= link_to 'My Todo-categories', categories_path, class: 'btn btn-primary' %>
<%= link_to 'My Todo-tasks', tasks_path, class: 'btn btn-primary' %>
</p>

<br>

<p>This todo-list is created for CVWO 2018 holiday assignment.</p>
<p>This todo-list is created by Zhang Yuntong.</p>